const port = process.argv[2] || "9223";
const viewportWidth = Number(process.argv[3] || 390);
const viewportHeight = Number(process.argv[4] || 844);
const pages = await fetch(`http://127.0.0.1:${port}/json`).then(response => response.json());
const page = pages.find(item => item.type === "page" && item.url.includes("127.0.0.1:8876"));
if (!page) throw new Error("没有找到 Atherloom 调试页面");
const socket = new WebSocket(page.webSocketDebuggerUrl);
await new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject; });
let sequence = 0;
const pending = new Map();
socket.onmessage = event => { const message = JSON.parse(event.data); if (message.id && pending.has(message.id)) { pending.get(message.id)(message); pending.delete(message.id); } };
function command(method, params = {}) { const id = ++sequence; socket.send(JSON.stringify({ id, method, params })); return new Promise(resolve => pending.set(id, resolve)); }
async function evaluate(expression) { const result = await command("Runtime.evaluate", { expression, awaitPromise: true, returnByValue: true }); if (result.result?.exceptionDetails) throw new Error(result.result.exceptionDetails.text); return result.result?.result?.value; }
const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
const check = async (name, expression) => { const ok = await evaluate(expression); if (!ok) throw new Error(`UI smoke failed: ${name}`); console.log(`PASS ${name}`); };

await command("Runtime.enable");
await command("Page.enable");
await command("Page.navigate", { url: `http://127.0.0.1:8876/?smoke=${Date.now()}` });
await wait(900);
await command("Emulation.setDeviceMetricsOverride", { width: viewportWidth, height: viewportHeight, deviceScaleFactor: 3, mobile: true });
await check("top bar keeps only call action", `!!document.querySelector('#openCall') && !document.querySelector('#shareChat') && !document.querySelector('#openMemory') && !document.querySelector('#topSettings')`);
await check("call action uses a visible non-emoji icon", `getComputedStyle(document.querySelector('#openCall')).display !== 'none' && !!document.querySelector('#openCall svg')`);
await check("persona picker remains visible on compact phone", `getComputedStyle(document.querySelector('#personaPicker')).display !== 'none'`);
await check("welcome mark uses themeable SVG", `!!document.querySelector('.sun-mark svg') && getComputedStyle(document.querySelector('.sun-mark')).color === 'rgb(201, 100, 66)'`);
await check("versioned service worker updater is present", `document.documentElement.innerHTML.includes('service-worker.js?v=27') && document.documentElement.innerHTML.includes("updateViaCache: 'none'")`);
await check("welcome and composer helper copy stay minimal", `!document.querySelector('#welcome p') && !document.querySelector('#prompt').hasAttribute('placeholder') && !document.querySelector('.disclaimer')`);
await check("morning greeting follows local time", `renderTimeGreeting(new Date(2026,6,19,8,0)) === '早上好，今天想聊些什么？'`);
await check("afternoon greeting follows local time", `renderTimeGreeting(new Date(2026,6,19,16,0)) === '下午好，想聊些什么？'`);
await check("late-night greeting follows local time", `renderTimeGreeting(new Date(2026,6,19,23,30)) === '夜深了，想聊些什么？'`);
await check("call overlay starts hidden", `document.querySelector('#callSpace').hidden === true`);
await evaluate(`window.AtherloomNative={showNotice:message=>window.__androidCallNotice=message};document.querySelector('#openCall').click()`);
await check("Android call guard avoids the blocking overlay", `document.querySelector('#callSpace').hidden === true && window.__androidCallNotice.includes('已阻止')`);
await evaluate(`delete window.AtherloomNative`);
await evaluate(`document.querySelector('#titleButton').click()`); await wait(100);
await check("conversation switcher opens from title", `!document.querySelector('#conversationPopover').hidden && !!document.querySelector('#conversationPopover [data-value="__new__"]')`);
await evaluate(`document.body.click()`); await wait(100);
await check("conversation switcher closes outside", `document.querySelector('#conversationPopover').hidden`);
const hasProviders = await evaluate(`state.providers.length > 0`);
await evaluate(`document.querySelector('#modelPicker').click()`); await wait(100);
if (hasProviders) {
  await check("model popover opens", `document.querySelector('#modelPopover').hidden === false`);
  await evaluate(`document.body.click()`); await wait(100);
  await check("model popover closes outside", `document.querySelector('#modelPopover').hidden === true`);
} else {
  await check("empty model picker opens API settings", `document.querySelector('#settingsPanel').classList.contains('open') && document.querySelector('#tab-providers').classList.contains('active')`);
await check("provider form supports fetching models", `!!document.querySelector('#fetchModels') && !!document.querySelector('#providerModelSelect')`);
await check("provider form exposes editable generation controls", `['temperature','top_p','max_tokens'].every(name=>!!document.querySelector('#providerForm [name='+name+']'))`);
await check("provider form exposes real streaming control", `!!document.querySelector('#providerForm [name=stream_enabled]') && document.querySelector('#providerForm [name=stream_enabled]').checked`);
await check("fetched models use a real mobile picker", `(()=>{const form=document.querySelector('#providerForm');showFetchedModels(['ds-v4-flash','ds-v4-pro'],form);const select=document.querySelector('#providerModelSelect');select.value='ds-v4-pro';select.dispatchEvent(new Event('change'));return !select.hidden&&select.options.length===3&&form.elements.model.value==='ds-v4-pro'})()`);
await check("existing provider can be edited without re-entering API key", `(()=>{const original=state.providers;state.providers=[{id:'edit-smoke',name:'DeepSeek',protocol:'deepseek',base_url:'https://api.deepseek.com',model:'deepseek-chat',custom_headers:'{}',temperature:.4,top_p:.9,max_tokens:4096,prompt_cache:true,thinking_enabled:true,stream_enabled:false,enabled:true,has_api_key:true}];renderSettings();document.querySelector('[data-edit-provider="edit-smoke"]').click();const form=document.querySelector('#providerForm');const ok=!form.hidden&&form.dataset.editing==='edit-smoke'&&form.elements.name.value==='DeepSeek'&&form.elements.model.value==='deepseek-chat'&&!form.elements.stream_enabled.checked&&form.elements.api_key.value===''&&document.querySelector('#connectionState').textContent.includes('保留原密钥');state.providers=original;delete form.dataset.editing;form.hidden=true;renderSettings();return ok})()`);
await check("existing persona opens in editable form", `(()=>{const original=state.personas;state.personas=[{id:'persona-smoke',name:'朋友',prompt:'你叫 Ara。'}];renderSettings();document.querySelector('[data-edit-persona="persona-smoke"]').click();const form=document.querySelector('#personaForm'),ok=form.dataset.editing==='persona-smoke'&&form.elements.name.value==='朋友'&&form.elements.prompt.value==='你叫 Ara。'&&document.querySelector('#savePersona').textContent==='保存修改'&&!document.querySelector('#cancelPersonaEdit').hidden;state.personas=original;form.reset();delete form.dataset.editing;document.querySelector('#savePersona').textContent='保存人格';document.querySelector('#cancelPersonaEdit').hidden=true;renderSettings();return ok})()`);
await check("Roll versions stay in one message position", `(()=>{window.__smokeMessages=state.messages;window.__smokeVersions=state.version_selection;state.messages=[{id:'u1',role:'user',content:'你好'},{role:'assistant',content:'第一版',parent_message_id:'u1',model:'m'},{role:'assistant',content:'第二版',parent_message_id:'u1',model:'m'}];state.version_selection={u1:0};renderMessages();const first=document.querySelector('#messages').textContent.includes('第一版')&&document.querySelector('.version-switcher span')?.textContent==='1 / 2';state.version_selection.u1=1;renderMessages();document.querySelector('[data-action=version-prev]').click();return first&&state.version_selection.u1===0&&document.querySelector('#messages').textContent.includes('第一版')})()`);
await check("message actions remain visible", `getComputedStyle(document.querySelector('.message-actions')).opacity==='1'`);
await check("short user bubble stays right aligned", `(()=>{const bubble=document.querySelector('.message.user .bubble').getBoundingClientRect(),area=document.querySelector('#messages').getBoundingClientRect();return bubble.right>area.left+area.width*.8})()`);
await check("streaming updates reuse the current message DOM", `(()=>{const message=visibleMessageVersions().find(item=>item.role==='assistant');const article=document.querySelector('.message.assistant');message.content='第一段';updateStreamingMessage(message);message.content+='第二段';updateStreamingMessage(message);return article===document.querySelector('.message.assistant')&&article.querySelector('.bubble').textContent==='第一段第二段'&&!article.textContent.includes('nullnull')})()`);
await check("message menu offers delete current version", `!!document.querySelector('#deleteMessageVersion') && document.querySelector('#deleteMessageVersion').textContent.includes('删除本版本')`);
await evaluate(`state.messages=window.__smokeMessages;state.version_selection=window.__smokeVersions;delete window.__smokeMessages;delete window.__smokeVersions;renderMessages()`);
  await evaluate(`document.querySelector('#settingsPanel [data-close]').click()`); await wait(100);
}
await evaluate(`document.querySelector('#mobileMenu').click()`); await wait(100);
await check("mobile sidebar opens", `document.querySelector('#sidebar').classList.contains('open') && !document.querySelector('#sidebarBackdrop').hidden`);
await evaluate(`document.querySelector('#sidebarBackdrop').click()`); await wait(100);
await check("mobile sidebar closes", `!document.querySelector('#sidebar').classList.contains('open') && document.querySelector('#sidebarBackdrop').hidden`);
await evaluate(`document.querySelector('#openGames').click()`); await wait(500);
await check("playable game cards exist", `!!document.querySelector('[data-game-id="claw_machine"]') && !!document.querySelector('[data-game-id="cloud_slots"]')`);
await evaluate(`document.querySelector('[data-game-id="claw_machine"]').click()`); await wait(300);
await check("claw machine opens", `document.querySelector('#clawStage').hidden === false`);
await evaluate(`document.querySelector('[data-game-id="cloud_slots"]').click()`); await wait(300);
await check("slots open", `document.querySelector('#slotsStage').hidden === false`);
await check("AI game controls enabled", `!document.querySelector('#aiGameControls').hidden && !document.querySelector('#aiPlayOne').disabled && !document.querySelector('#aiPlayThree').disabled`);
await evaluate(`document.querySelector('#closeGames').click(); document.querySelector('#openReading').click()`); await wait(100);
await check("reading room opens", `!document.querySelector('#mediaSpace').hidden && !document.querySelector('#readingRoom').hidden`);
await check("small text book opens without blocking", `(async()=>{await openLocalBook(new File([['第一章','你好'].join(String.fromCharCode(10))], 'test.txt', {type:'text/plain'}));return document.querySelector('#bookReader pre')?.textContent.includes('第一章') && document.querySelector('#bookStatus').textContent.includes('本地文件')})()`);
await check("Android PDF is safely blocked", `(async()=>{window.AtherloomNative={showNotice(){}};await openLocalBook(new File(['%PDF'], 'test.pdf', {type:'application/pdf'}));delete window.AtherloomNative;return document.querySelector('#bookStatus').textContent.includes('安全拦截') && document.querySelector('#bookReader').textContent.includes('安卓暂不在应用内打开 PDF')})()`);
await evaluate(`document.querySelector('#closeMedia').click(); document.querySelector('#openCinema').click()`); await wait(100);
await check("cinema room opens", `!document.querySelector('#mediaSpace').hidden && !document.querySelector('#cinemaRoom').hidden`);
await evaluate(`document.querySelector('#closeMedia').click()`);
await command("Page.navigate", { url: `http://127.0.0.1:8876/?standalone=1&branch-smoke=${Date.now()}` });
await wait(900);
await check("Standalone branch creates and opens a copied conversation", `(async()=>{const sourceId='branch-source',userId='branch-user',assistantId='branch-assistant',now=new Date().toISOString();localStorage.setItem('atherloom:conversations',JSON.stringify([{id:sourceId,title:'原对话',provider_id:null,persona_id:null,summary:'',created_at:now,updated_at:now,pinned:0,starred:0,archived:0}]));localStorage.setItem('atherloom:messages:'+sourceId,JSON.stringify([{id:userId,role:'user',content:'分支起点',created_at:now},{id:assistantId,role:'assistant',content:'分支回答',parent_message_id:userId,created_at:now}]));const response=await fetch('/api/conversations/'+sourceId+'/branch/'+assistantId,{method:'POST',body:'{}'}),conversation=await response.json(),copied=JSON.parse(localStorage.getItem('atherloom:messages:'+conversation.id)||'[]');return response.ok&&conversation.id!==sourceId&&conversation.title==='原对话 · 分支'&&copied.length===2&&copied[0].id!==userId&&copied[1].parent_message_id===copied[0].id})()`);
socket.close();
